<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <div class="row justify-content-center border border-secondary rounded  m-1">
        <a class="p-4 h5" href="/">買い物を続ける</a>
    </div>
    <!-- カート内商品一覧 -->
    <div class="border border-secondary rounded  m-1 ">
        <div class="col-sm-12 mb-4">
            <?php if (!empty($_SESSION['cart'])) : ?>
            <!-- カート内の商品数 -->
            <h4 class="d-flex justify-content-end align-items-center m-3">
                <span class="text-muted">カート</span>
                <span class="badge badge-secondary badge-pill"><?= count($_SESSION['cart']) ?? 0; ?></span>
            </h4>
            <!-- 商品 -->
            <?php foreach ($_SESSION['cart'] as $index => $item) : ?>
                <div class="row">
                    <ul class="list-group">
                        <li class="list-group-item justify-content-between d-lg-flex align-items-center mb-3">
                            <img src="<?= $item['image_dir'] ?>" alt="商品画像" class="col-lg-2 col-md-12 img-fluid">
                            <span class="col-lg-3 col-md-6"><?= $item['product_name'] ?></span>
                            <span class="col-lg-2 col-md-6"><?= yen($item['price']) ?></span>
                            <form class="col-lg-3 col-md-12" action="/cart/update" method="post">
                                <select name="order_quantity">
                                    <?php
                                    for ($i = 1; $i <= $item['stock']; $i++) {
                                        echo "<option value=$i ";
                                        if ($item['order_quantity'] == $i) {
                                            echo "selected";
                                        }
                                        echo ">$i</option>";
                                    }
                                    ?>
                                </select>
                                <input type="hidden" name="index" value="<?= $index ?>">
                                <button class="btn btn-primary">更新</button>
                                <a class="btn btn-danger" role="button" href=/cart/<?= $index ?>>削除</a>
                            </form>
                            <span class="col-lg-3 col-md-12">小計 :<?= yen($item['miner_total']) ?></span>
                        </li>
                    </ul>
                </div>
            <?php endforeach; ?>
            <span class="h4 row pr-4 justify-content-end">合計 :<?= yen($_SESSION['carts']['total']) ?></span>
        </div>
    </div>
    <div class="row justify-content-end border border-secondary rounded  m-1">
        <a class="h5 p-4" href="/order">購入</a>
    </div>
    <?php else : ?>
        <p class="p-4 h5 text-center">ショッピングカートに商品は入っていません。</p>
    <?php endif; ?>
</div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
