<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<h3>カート</h3>

<div>
    <a href="/">買い物を続ける</a>
</div>
<div>
    <div class="h3">カートの中身</div>
    <?php if (!empty($_SESSION['cart'])) : ?>
        <?php foreach ($_SESSION['cart'] as $index => $item) : ?>
            <img src="<?= $item['image_dir'] ?>" alt="商品画像" width="100" height="100">
            <label for="product">商品名 :</label><?= $item['product_name'] ?>
            <label for="product">価格 :</label><?= yen($item['price']) ?>
            <form action="/order/cart/update" method="post">
                <select name="order_quantity">
                    <?php
                    for ($i = 1; $i <= $item['stock']; $i++) {
                        echo "<option value=$i ";
                        if ($item['order_quantity'] == $i) {
                            echo "selected";
                        }
                        echo ">$i</option>";
                    }
                    ?>
                </select>
                <input type="hidden" name="index" value="<?= $index ?>">
                <button>更新</button>
            </form>
            <a href=/order/cart/<?= $index ?>>削除</a>
            <label for="product">小計 :</label><?= yen($item['miner_total']) ?>
            <hr>
        <?php endforeach; ?>
        <label for="product">合計 :</label><?= yen($_SESSION['carts']['total']) ?>
    <?php else : ?>
        <p>ショッピングカートに商品は入っていません。</p>
    <?php endif; ?>
</div>
<div>
    <a href="/order/addressee">購入</a>
</div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
