<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <div class="row justify-content-center border border-secondary rounded  m-1">
        <a class="p-4 h5" href="/">買い物を続ける</a>
    </div>
    <div class="border border-secondary rounded  m-1 ">
        <div class="col-sm-12 order-md-2 mb-4">
            <!-- カート内商品一覧 -->
            <?php if (!empty($_SESSION['cart'])) : ?>
            <!-- カート内の商品数 -->
            <h4 class="d-flex justify-content-end align-items-center m-3">
                <span class="text-muted">カート</span>
                <span class="badge badge-secondary badge-pill"><?= count($_SESSION['cart']) ?? 0; ?></span>
            </h4>
            <!-- 商品 -->
            <?php foreach ($_SESSION['cart'] as $index => $item) : ?>
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <img src="<?= $item['image_dir'] ?>" alt="商品画像" width="100"
                             height="100">
                        <span>商品名 :<?= $item['product_name'] ?></span>
                        <span><?= yen($item['price']) ?></span>
                        <form action="/cart/update" method="post">
                            <select name="order_quantity">
                                <?php
                                for ($i = 1; $i <= $item['stock']; $i++) {
                                    echo "<option value=$i ";
                                    if ($item['order_quantity'] == $i) {
                                        echo "selected";
                                    }
                                    echo ">$i</option>";
                                }
                                ?>
                            </select>
                            <input type="hidden" name="index" value="<?= $index ?>">
                            <button class="btn btn-primary">更新</button>
                            <a class="btn btn-danger" href=/cart/<?= $index ?>>削除</a>
                        </form>
                        <span>小計 :<?= yen($item['miner_total']) ?></span>
                        <hr>
                    </li>
                </ul>
            <?php endforeach; ?>
            <label for="product">合計 :</label><?= yen($_SESSION['carts']['total']) ?>
        </div>
    </div>
    <div>
        <a href="/order">購入</a>
    </div>
    <?php else : ?>
        <p class="p-4 h5 text-center">ショッピングカートに商品は入っていません。</p>
    <?php endif; ?>
</div>

    <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <!-- <h2>Checkout form</h2> -->
        <h2>申し込みフォーム</h2>
        <!-- <p class="lead">Below is an example form built entirely with Bootstrap's form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p> -->
        <p class="lead">これは Bootstrap のフォーム操作によって作成されたサンプルフォームです。各フォームグループは内容を埋めずに提出しようとした際にバリデーションが行われます。</p>
    </div>

    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <!-- <span class="text-muted">Your cart</span> -->
                <span class="text-muted">カート</span>
                <span class="badge badge-secondary badge-pill">3</span>
            </h4>
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <!-- <h6 class="my-0">Product name</h6> -->
                        <h6 class="my-0">商品名</h6>
                        <!-- <small class="text-muted">Brief description</small> -->
                        <small class="text-muted">簡単な説明</small>
                    </div>
                    <span class="text-muted">1200 円</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <!-- <h6 class="my-0">Second product</h6> -->
                        <h6 class="my-0">2つ目の商品</h6>
                        <!-- <small class="text-muted">Brief description</small> -->
                        <small class="text-muted">簡単な説明</small>
                    </div>
                    <span class="text-muted">800 円</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <!-- <h6 class="my-0">Third item</h6> -->
                        <h6 class="my-0">3つ目のアイテム</h6>
                        <!-- <small class="text-muted">Brief description</small> -->
                        <small class="text-muted">簡単な説明</small>
                    </div>
                    <span class="text-muted">500 円</span>
                </li>
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                        <h6 class="my-0">プロモーションコード</h6>
                        <!-- <h6 class="my-0">Promo code</h6> -->
                        <small>EXAMPLECODE</small>
                    </div>
                    <span class="text-success">-500 円</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <!-- <span>Total (円)</span> -->
                    <span>合計金額</span>
                    <strong>2000 円</strong>
                </li>
            </ul>

            <form class="card p-2">
                <div class="input-group">
                    <!-- <input type="text" class="form-control" placeholder="Promo code"> -->
                    <input type="text" class="form-control" placeholder="プロモーションコード">
                    <div class="input-group-append">
                        <!-- <button type="submit" class="btn btn-secondary">Redeem</button> -->
                        <button type="submit" class="btn btn-secondary">適用する</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-8 order-md-1">
            <!-- <h4 class="mb-3">Billing address</h4> -->
            <h4 class="mb-3">請求先</h4>
            <form class="needs-validation" novalidate>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <!-- <label for="firstName">First name</label> -->
                        <label for="firstName">名字</label>
                        <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            <!-- Valid first name is required. -->
                            名字を入力してください。
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <!-- <label for="lastName">Last name</label> -->
                        <label for="lastName">名前</label>
                        <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            <!-- Valid last name is required. -->
                            名前を入力してください。
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <!-- <label for="username">Username</label> -->
                    <label for="username">ユーザーネーム</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="text" class="form-control" id="username" placeholder="Username" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            <!-- Your username is required. -->
                            ユーザーネームを入力してください。
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <!-- <label for="email">Email <span class="text-muted">(Optional)</span></label> -->
                    <label for="email">メールアドレス <span class="text-muted">（オプション）</span></label>
                    <input type="email" class="form-control" id="email" placeholder="you@example.com">
                    <div class="invalid-feedback">
                        <!-- Please enter a valid email address for shipping updates. -->
                        有効なメールアドレスを入力してください。
                    </div>
                </div>

                <div class="mb-3">
                    <!-- <label for="address">Address</label> -->
                    <label for="address">送り先住所</label>
                    <!-- <input type="text" class="form-control" id="address" placeholder="1234 Main St" required> -->
                    <input type="text" class="form-control" id="address" placeholder="東京都千代田区千代田1-1" required>
                    <div class="invalid-feedback">
                        <!-- Please enter your shipping address. -->
                        送り先住所を入力してください。
                    </div>
                </div>

                <div class="mb-3">
                    <!-- <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label> -->
                    <label for="address2">住所2 <span class="text-muted">（オプション）</span></label>
                    <!-- <input type="text" class="form-control" id="address2" placeholder="Apartment or suite"> -->
                    <input type="text" class="form-control" id="address2" placeholder="アパートやマンション名">
                </div>

                <div class="row">
                    <div class="col-md-5 mb-3">
                        <!-- <label for="country">Country</label> -->
                        <label for="country">国</label>
                        <select class="custom-select d-block w-100" id="country" required>
                            <!-- <option value="">Choose...</option> -->
                            <option value="">選択してください</option>
                            <!-- <option>United States</option> -->
                            <option>日本</option>
                        </select>
                        <div class="invalid-feedback">
                            <!-- Please select a valid country. -->
                            有効な国を選択してください。
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <!-- <label for="state">State</label> -->
                        <label for="state">都道府県</label>
                        <select class="custom-select d-block w-100" id="state" required>
                            <!-- <option value="">Choose...</option> -->
                            <option value="">選択してください</option>
                            <!-- <option>California</option> -->
                            <option>東京都</option>
                        </select>
                        <div class="invalid-feedback">
                            <!-- Please provide a valid state. -->
                            有効な都道府県を入力してください。
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <!-- <label for="zip">Zip</label> -->
                        <label for="zip">郵便番号</label>
                        <input type="text" class="form-control" id="zip" placeholder="" required>
                        <div class="invalid-feedback">
                            <!-- Zip code required. -->
                            郵便番号を入力してください。
                        </div>
                    </div>
                </div>
                <hr class="mb-4">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="same-address">
                    <!-- <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label> -->
                    <label class="custom-control-label" for="same-address">送り先は請求先と同じ</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="save-info">
                    <!-- <label class="custom-control-label" for="save-info">Save this information for next time</label> -->
                    <label class="custom-control-label" for="save-info">保存して次回からの入力を省略する</label>
                </div>
                <hr class="mb-4">

                <!-- <h4 class="mb-3">Payment</h4> -->
                <h4 class="mb-3">支払い方法</h4>

                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                        <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked
                               required>
                        <!-- <label class="custom-control-label" for="credit">Credit card</label> -->
                        <label class="custom-control-label" for="credit">クレジットカード</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                        <!-- <label class="custom-control-label" for="debit">Debit card</label> -->
                        <label class="custom-control-label" for="debit">デビットカード</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                        <!-- <label class="custom-control-label" for="paypal">PayPal</label> -->
                        <label class="custom-control-label" for="paypal">ペイパル</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <!-- <label for="cc-name">Name on card</label> -->
                        <label for="cc-name">カードに書かれている名前</label>
                        <input type="text" class="form-control" id="cc-name" placeholder="" required>
                        <!-- <small class="text-muted">Full name as displayed on card</small> -->
                        <small class="text-muted">カード表面に書かれているフルネーム</small>
                        <div class="invalid-feedback">
                            <!-- Name on card is required -->
                            カードに書かれている名前を入力してください
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <!-- <label for="cc-number">Credit card number</label> -->
                        <label for="cc-number">クレジットカード番号</label>
                        <input type="text" class="form-control" id="cc-number" placeholder="" required>
                        <div class="invalid-feedback">
                            <!-- Credit card number is required -->
                            クレジットカード番号を入力してください
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <!-- <label for="cc-expiration">Expiration</label> -->
                        <label for="cc-expiration">有効期限</label>
                        <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                        <div class="invalid-feedback">
                            <!-- Expiration date required -->
                            有効期限を入力してください
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="cc-cvv">CVV</label>
                        <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                        <div class="invalid-feedback">
                            <!-- Security code required -->
                            セキュリティコードを入力してください
                        </div>
                    </div>
                </div>
                <hr class="mb-4">
                <!-- <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button> -->
                <button class="btn btn-primary btn-lg btn-block" type="submit">申込みを続ける</button>
            </form>
        </div>
    </div>

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 Company Name</p>
        <ul class="list-inline">
            <!-- <li class="list-inline-item"><a href="#">Privacy</a></li> -->
            <li class="list-inline-item"><a href="#">プライバシー</a></li>
            <!-- <li class="list-inline-item"><a href="#">Terms</a></li> -->
            <li class="list-inline-item"><a href="#">利用規約</a></li>
            <!-- <li class="list-inline-item"><a href="#">Support</a></li> -->
            <li class="list-inline-item"><a href="#">サポート</a></li>
        </ul>
    </footer>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
