<!-- ヘッダー読み込み -->
<?= $this->fetch('header.phtml') ?>

<!--ニュース-->
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto">
        <h1 class="display-5">News</h1>
        <dl>
            <dt>2020-6-18</dt>
            <dd>食いしん坊なコアラが仲間入りしました</dd>
        </dl>
        <hr>
        <dl>
            <dt>2020-5-15</dt>
            <dd>器用なラッコが仲間入りしました</dd>
        </dl>
        <hr>
        <dl>
            <dt>2020-4-17</dt>
            <dd>フカフカのアルパカが仲間入りしました</dd>
        </dl>
        <hr>
    </div>
</div>
<!--商品-->
<div class="card-group">
    <?php foreach ($products as $product): ?>
        <div class="cardtext-white col-lg-3 col-md-4 col-sm-12 p-0">
            <a class="text-white" href="/item/<?= $product['product_id'] ?>">
                <img class="card-img" src="<?= '/image/file/' . $product['image_dir'] ?>" alt="商品画像">

                <div class="card-img-overlay">
                    <h5 class="card-title"><?= $product['product_name'] ?></h5>
                    <p class="card-text">price : <?= yen($product['price']) ?></p>
                    <p class="card-text">stock : <?= stock_confirmation($product['stock']) ?></p>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>