<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<h3>商品管理</h3>

<form action="/product/<?= $product['product_id'] ?>" method="post" enctype="multipart/form-data">
    <label>商品名:</label><input type="text" name="product_name" value="<?= $product['product_name'] ?>">
    <label>価格:</label><input type="number" name="price" value="<?= $product['price'] ?>">
    <label>在庫数:</label><input type="number" name="stock" value="<?= $product['stock'] ?>">
    <label>説明文:</label><textarea name="description" cols="30" rows="10"><?= $product['description'] ?></textarea>
    <label>商品画像:</label><input type="file" name="image_dir" accept=".jpg, jpeg, png">

    <button>更新</button>
    <button name="_METHOD" value="delete" onclick="return confirm('本当に削除しますか？')">削除</button>
</form>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>