<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <div class="py-5 text-center">
        <h2>商品一覧</h2>
    </div>

    <table class="table table-hover">
        <caption>商品一覧</caption>
        <thead>
        <tr>
            <th>商品番号</th>
            <th scope="col">商品名</th>
            <th scope="col">価格</th>
            <th scope="col">在庫</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($products as $product): ?>
            <tr data-href="/product/<?= $product['product_id'] ?>">
                <th scope="row"><?= ($product['product_id']) ?></th>
                <td><?= e($product['product_name']) ?></td>
                <td><?= $product['price'] ?></td>
                <td><?= stock_confirmation($product['stock']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>