<!-- 管理者以外は入れない -->
<?php isAdmin(); ?>
<!-- ヘッダー -->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <div class="py-5 text-center">
        <h2>商品一覧</h2>
    </div>

    <table class="table table-hover">
        <caption>商品一覧</caption>
        <thead>
        <tr>
            <th>商品番号</th>
            <th scope="col">商品名</th>
            <th scope="col" class="text-right">価格</th>
            <th scope="col" class="text-right">在庫</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($products as $product): ?>
            <tr data-href="/product/<?= $product['product_id'] ?>">
                <th scope="row"><?= ($product['product_id']) ?></th>
                <td><?= e($product['product_name']) ?></td>
                <td class="text-right"><?= yen($product['price']) ?></td>
                <td class="text-right"><?= stock_confirmation($product['stock']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row m-1">
        <a role="button" class="text-white btn btn-success btn-lg btn-block" href="/product/create">商品追加</a>
    </div>
</div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>