<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>うきうきショッピング</title>
</head>
<body>
<header>
    <h3>うきうきショッピング</h3>
    <navi>
        <a href="/">トップ</a>
        <a href="/product">商品管理画面</a>
        <a href="/cart">カート</a>
        <a href="/login">ログイン</a>
        <a href="/signup">新規登録</a>
    </navi>
    <a href="">
        <?= $_SESSION['user']['login_id'] ?? 'guest'; ?>
    </a>
    <a href="/logout">ログアウト</a>
</header>
<body>