<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- ファビコン -->
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap-reboot.css">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">

    <title>ウキウキshopping</title>
</head>

<body>
<div class="container-fluid">
    <!--　ヘッダ　-->
    <header>
        <nav class="navbar navbar-expand-sm navbar-light flex-sm-column m-4">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- サイトロゴ -->
            <a class="navbar-brand" href="/">
            <img src="/logo.png" width="150" height="150" alt="ロゴ画像">
            </a>
            <!-- ナビゲーションバー -->
            <div class="collapse navbar-collapse justify-content-space-between" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link h5" href="/">ホーム
                            <svg class="bi bi-house-fill" width="1em" height="1em" viewBox="0 0 16 16"
                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M8 3.293l6 6V13.5a1.5 1.5 0 01-1.5 1.5h-9A1.5 1.5 0 012 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z"
                                      clip-rule="evenodd"/>
                                <path fill-rule="evenodd"
                                      d="M7.293 1.5a1 1 0 011.414 0l6.647 6.646a.5.5 0 01-.708.708L8 2.207 1.354 8.854a.5.5 0 11-.708-.708L7.293 1.5z"
                                      clip-rule="evenodd"/>
                            </svg>
                            <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link h5" href="/cart">カート
                            <svg class="bi bi-credit-card" width="1em" height="1em" viewBox="0 0 16 16"
                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M14 3H2a1 1 0 00-1 1v8a1 1 0 001 1h12a1 1 0 001-1V4a1 1 0 00-1-1zM2 2a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V4a2 2 0 00-2-2H2z"
                                      clip-rule="evenodd"/>
                                <rect width="3" height="3" x="2" y="9" rx="1"/>
                                <path d="M1 5h14v2H1z"/>
                            </svg>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle h5" href="#" id="navbarDropdownMenuLink" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            アカウント
                            <svg class="bi bi-people-circle" width="1em" height="1em" viewBox="0 0 16 16"
                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 008 15a6.987 6.987 0 005.468-2.63z"/>
                                <path fill-rule="evenodd" d="M8 9a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd"
                                      d="M8 1a7 7 0 100 14A7 7 0 008 1zM0 8a8 8 0 1116 0A8 8 0 010 8z"
                                      clip-rule="evenodd"/>
                            </svg>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/login">ログイン</a>
                            <a class="dropdown-item" href="/logout">ログアウト</a>
                            <a class="dropdown-item" href="/signup">新規登録</a>
                        </div>
                    </li>
                </ul>
            </div>

            <a href="/product">商品管理画面</a>
        </nav>
    </header>
