<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<h3>カート</h3>

<div>
    <a href="/">買い物を続ける</a>
</div>
<div>
    <div class="h3">カートの中身</div>
    <img src="<?= '/image/' . $product['image_dir'] ?>" alt="商品画像" width="90" height="90">
    <?= $product['product_name'] ?>
    <?= $product['price'] ?>
    <?= $product['order_quantity'] ?>
    <!--    TODO: 購入個数を変更できるようにする-->
    <input type="button" value="削除">
    <!--    TODO 変更した個数に合計金額を連動させる-->
    <text><?= $product['price'] * $product['order_quantity'] ?></text>
    <div>
        <!--TODO: 複数の商品の合計を計算する-->
        <div class="h3">合計 : <?= $product['price'] * $product['order_quantity'] ?></div>
    </div>
</div>
    <div>
        <a href="">購入</a>
    </div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>