<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>
<div class="container">
    <h3>購入確認</h3>

    <div class="row justify-content-center border border-secondary rounded  m-1">
        <a class="p-4 h5" href="/">買い物を続ける</a>
    </div>
    <!-- カート内商品一覧 -->
    <div class="border border-secondary rounded  m-1 ">
        <div class="col-sm-12 mb-4">
            <?php foreach ($_SESSION['cart'] as $index => $item) : ?>
                <div class="row">
                    <ul class="list-group">
                        <li class="list-group-item justify-content-between d-lg-flex align-items-center mb-3">
                            <img class="col-lg-2 col-md-12 img-fluid" src="<?= $item['image_dir'] ?>"
                                 alt="商品画像">
                            <span class="col-lg-3 col-md-6">商品名: <?= $item['product_name'] ?></span>
                            <span class="col-lg-2 col-md-6">価格 : <?= yen($item['price']) ?></span>
                            <span class="col-lg-3 col-md-12">数量 :<?= $item['order_quantity'] ?></span>
                            <span class="col-lg-3 col-md-12">小計 :<?= yen($item['miner_total']) ?></span>
                        </li>
                    </ul>
                </div>
            <?php endforeach; ?>
            <!-- 合計金額 --->
            <span class="h4 row pr-4 justify-content-end">合計 :<?= yen($_SESSION['carts']['total']) ?></span>
        </div>
    </div>
    <?php if (isset($_SESSION['user'])) : ?>
        <div class="row m-1">
            <a role="button" class="text-white btn btn-primary btn-lg btn-block" href="/order/submit"
               onclick="return confirm('本当に購入しますか？')">購入確定</a>
        </div>
    <?php else: ?>
        購入するには<a href="/login">ログイン</a>してください。
    <?php endif; ?>
</div>

<!--フッター-->
<?= $this->fetch('footer.phtml') ?>