<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <div class="display-1">admin</div>
    <form action="/login" method="post" class="form-signin">
        <h1 class="h3 mb-3 font-weight-normal">ログイン</h1>
        <label for="inputName" class="sr-only">ログイン名</label>
        <input type="text" name="login_id" id="inputName" class="form-control" placeholder="ログイン名" required autofocus>
        <label for="inputPassword" class="sr-only">パスワード</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="パスワード" required>
        <?php if (isset($data['auth_error'])): ?>
            <span class="text-danger d-block small"><?= $data['auth_error']; ?></span>
        <?php endif; ?>
        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" value="remember-me" id="rememberCheck">
            <label class="form-check-label" for="rememberCheck">
                状態を記憶する
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">ログインする</button>
        <a href="/signup">未登録の場合は新規登録してください</a>

    </form>
</div>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
