<!-- 未登録者は入れない -->
<?php isLogin(); ?>

<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <!-- ユーザプロファイル -->
    <div class="border border-secondary rounded  m-1">
        <!-- タブ部分 -->
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                   aria-controls="profile" aria-selected="true">利用者情報</a>
                <a class="nav-item nav-link" id="history-tab" data-toggle="tab" href="#history" role="tab"
                   aria-controls="history" aria-selected="false">購入履歴</a>
            </div>
        </nav>

        <!-- パネル部分 -->
        <div class="tab-content mt-3" id="nav-tabContent">
            <!-- ユーザ情報 -->
            <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="col-md-12">
                    <form class="needs-validation" action="/user" method="post"
                          enctype="multipart/form-data">
                        <label for="productName">名前</label>
                        <input type="text" class="form-control" name="login_id" id="login_id"
                               placeholder=""
                               value="<?= $user['login_id'] ?>"
                               required>
                        <div class="invalid-feedback">
                            ユーザ名を入力して下さい
                        </div>
                        <?php if (isset($data['auth_error'])): ?>
                            <span class="text-danger d-block small"><?= $data['auth_error']; ?></span>
                        <?php endif; ?>
                        <label for="productName">パスワード</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder=""
                               value="<?= $user['password'] ?>"
                               required>
                        <div class="invalid-feedback">
                            パスワードを入力してください
                        </div>
                        <input type="hidden" name="user_id" id="user_id" value="<?= $user['user_id'] ?>">
                        <?php if (isset($data['password_error'])): ?>
                            <span class="text-danger d-block small"><?= $data['password_error']; ?></span>
                        <?php endif; ?>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block imageSubmit" type="submit">利用者情報の更新</button>
                        <button class="btn btn-danger btn-lg btn-block mb-3" name="_METHOD" value="delete"
                                onclick="return confirm('本当に削除しますか？')">利用者情報の削除
                        </button>
                    </form>
                </div>
            </div>

            <!-- 購入履歴 -->
            <div class="tab-pane" id="history" role="tabpanel" aria-labelledby="history-tab">
                <div class="col-md-12">
                    <?php if (!empty($data['history'])) : ?>
                        <!-- 商品 -->
                        <?php $buy_day = null; ?>
                        <?php foreach ($data['history'] as $item) : ?>
                            <div class="row">
                                <ul class="flex-fill">
                                    <?php
                                    if ($item['order_date'] != $buy_day && $buy_day != null) {
                                        echo "<hr>";
                                    }
                                    ?>
                                    <li class="d-sm-flex  justify-content-end align-items-center">
                                        <?php if ($item['order_date'] != $buy_day)  : ?>
                                            <p class="col-sm-2">購入日<?= $item['order_date'] ?></p>
                                        <?php endif; ?>
                                        <p class="col-sm-3"><?= $item['product_name'] ?></p>
                                        <p class="col-sm-3"><?= yen($item['price']) ?>円</p>
                                        <p class="col-sm-2 "><?= $item['order_quantity'] ?>個</p>
                                        <img class="col-sm-2 img-fluid"
                                             src="<?= '/image/file/' . $item['image_dir'] ?>"
                                             alt="商品画像">
                                    </li>
                                </ul>
                            </div>
                            <?php $buy_day = $item['order_date']; ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <p class="h5 p-4 mt-2 text-center">購入履歴はありません。</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
