<!-- 未登録者は入れない -->
<?php isLogin(); ?>

<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>


<div class="container">
    <!-- ユーザプロファイル -->
    <div class="border border-secondary rounded  m-1">
        <!-- タブ部分 -->
        <ul id="myTab" class="nav nav-tabs" role="tablist">
            <li class="nav-item" role="presentation">
                <a href="#profile" id="profile-tab" class="nav-link" role="tab" data-toggle="tab"
                   aria-controls="profile" aria-selected="false">利用者情報</a>
            </li>
            <li class="nav-item" role="presentation">
                <a href="#history" id="history-tab" class="nav-link" role="tab" data-toggle="tab"
                   aria-controls="history" aria-selected="false">購入履歴</a>
            </li>
        </ul>

        <!-- パネル部分 -->
        <div id="myTabContent" class="tab-content mt-3">
            <!-- ユーザ情報 -->
            <div id="profile" class="tab-pane" role="tabpanel" aria-labelledby="profile-tab">
                <div class="col-md-12 order-md-1">
                    <form class="needs-validation" action="/user" method="post"
                          enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="productName">名前</label>
                                <input type="text" class="form-control" name="login_id" id="login_id"
                                       placeholder=""
                                       value="<?= $user['login_id'] ?>"
                                       required>
                                <div class="invalid-feedback">
                                    ユーザ名を入力して下さい
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="productName">パスワード</label>
                                <input type="password" class="form-control" name="password" id="password" placeholder=""
                                       value="<?= $user['password'] ?>"
                                       required>
                                <div class="invalid-feedback">
                                    パスワードを入力してください
                                </div>
                            </div>
                            <input type="hidden" name="user_id" id="user_id" value="<?= $user['user_id'] ?>">
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block imageSubmit" type="submit">更新</button>
                        <button class="btn btn-danger btn-lg btn-block mb-3" name="_METHOD" value="delete"
                                onclick="return confirm('本当に削除しますか？')">削除
                        </button>
                    </form>
                </div>
            </div>

            <!-- 購入履歴 -->
            <div id="history" class="tab-pane" role="tabpanel" aria-labelledby="history-tab">
                <div class="col-sm-12">
                    <?php if (!empty($data['history'])) : ?>
                    <!-- 商品 -->
                    <?php $buy_day = null; ?>
                    <?php foreach ($data['history'] as $item) : ?>
                        <?php
                        if ($item['order_date'] != $buy_day) {
                            echo "<hr>";
                        }
                        ?>
                        <div class="row">
                            <ul class="" style="width: 100%">
                                <li class="justify-content-end d-lg-flex align-items-center">
                                    <?php if ($item['order_date'] != $buy_day)  : ?>
                                        <hr>
                                        <span class="col-lg-3 col-md-6">購入日<?= $item['order_date'] ?></span>
                                    <?php endif; ?>
                                    <span class="col-lg-3 col-md-6"><?= $item['product_name'] ?></span>
                                    <span class="col-lg-2 col-md-6">小計<?= yen($item['price']) ?>円</span>
                                    <span class="col-lg-2 col-md-6"><?= $item['order_quantity'] ?>個</span>
                                    <img class="col-lg-2 col-md-12 img-fluid"
                                         src="<?= '/image/file/' . $item['image_dir'] ?>"
                                         alt="商品画像">
                                </li>
                            </ul>
                        </div>
                        <?php $buy_day = $item['order_date']; ?>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>
