<!-- 未登録者は入れない -->
<?php isLogin(); ?>

<!--ヘッダー-->
<?= $this->fetch('header.phtml') ?>

<div class="container">
    <!-- ユーザプロファイル -->
    <div class="border border-secondary rounded  m-1">
        <!-- タブ部分 -->
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                   aria-controls="profile" aria-selected="true">利用者情報</a>
                <a class="nav-item nav-link" id="history-tab" data-toggle="tab" href="#history" role="tab"
                   aria-controls="history" aria-selected="false">購入履歴</a>
            </div>
        </nav>

        <!-- パネル部分 -->
        <div class="tab-content mt-3" id="nav-tabContent">
            <!-- ユーザ情報 -->
            <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="col-md-12">
                    <form class="needs-validation" action="/user" method="post"
                          enctype="multipart/form-data">
                        <label for="productName">名前</label>
                        <p><?= $user['login_id'] ?></p>
                        <label for="productName">パスワード</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder=""
                            <?php if (isset($user['password'])) : ?>
                               value="<?= $user['password'] ?>" required>
                            <?php else: ?>
                                required>
                            <?php endif ?>
                        <div class="invalid-feedback">
                            パスワードを入力してください
                        </div>
                        <?php if (isset($data['error']['password_error'])) : ?>
                            <span class="text-danger d-block small"><?= $data['error']['password_error']; ?></span>
                        <?php endif; ?>
                        <hr class="mb-4">
                        <input type="hidden" name="user_id" id="user_id"
                            <?php if (isset($user['user_id'])) : ?>
                               value="<?= $user['user_id'] ?>"
                        <?php endif ?>
                               required>
                        <button class="btn btn-primary btn-lg btn-block imageSubmit" type="submit">パスワードの変更</button>
                        <button class="btn btn-danger btn-lg btn-block mb-3" name="_METHOD" value="delete"
                                onclick="return confirm('本当に削除しますか？')">利用者情報の削除
                        </button>
                    </form>
                </div>
            </div>

            <!-- 購入履歴 -->
            <div class="tab-pane" id="history" role="tabpanel" aria-labelledby="history-tab">
                <?php if (!empty($data['history'])) : ?>
                    <!-- 商品 -->
                    <?php $buy_day = null; ?>
                    <div class="table-responsive">
                        <table class="table text-nowrap">
                            <thead>
                            <tr class="d-md-flex">
                                <th class="col-2">購入日</th>
                                <th class="col-3 text-left">商品名</th>
                                <th class="col-3 text-right">価格</th>
                                <th class="col-2 text-right">購入数</th>
                                <th class="col-2 text-center">画像</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($data['history'] as $item) : ?>
                                <tr class="d-md-flex">
                                    <td class="col-2">
                                        <?php if ($item['order_date'] != $buy_day)  : ?>
                                            <?= $item['order_date'] ?>
                                        <?php endif; ?>
                                    </td>
                                    <td class="col-3 text-left"><?= e($item['product_name']) ?></td>
                                    <td class="col-3 text-right"><?= yen($item['price']) ?></td>
                                    <td class="col-2 text-right"><?= $item['order_quantity'] ?></td>
                                    <td class="col-2">
                                        <img class="img-thumbnail"
                                             src="<?= '/image/file/' . $item['image_dir'] ?>"
                                             alt="商品画像">
                                    </td>
                                </tr>
                                <?php $buy_day = $item['order_date']; ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php else: ?>
                    <p class="h5 p-4 mt-2 text-center">購入履歴はありません。</p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!--フッター-->
<?= $this->fetch('footer.phtml') ?>